// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stiffiner_Inspection.Contexts;

#nullable disable

namespace Stiffiner_Inspection.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240326121107_refix db")]
    partial class refixdb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Stiffiner_Inspection.Models.Entity.Data", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Camera")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("camera");

                    b.Property<int?>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("client_id");

                    b.Property<int?>("Index")
                        .HasColumnType("int")
                        .HasColumnName("index");

                    b.Property<string>("Model")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("model");

                    b.Property<int?>("ResultArea")
                        .HasColumnType("int")
                        .HasColumnName("result_area");

                    b.Property<int?>("ResultLine")
                        .HasColumnType("int")
                        .HasColumnName("result_line");

                    b.Property<string>("Side")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("side");

                    b.Property<int?>("TargetId")
                        .HasColumnType("int")
                        .HasColumnName("target_id");

                    b.Property<DateTime?>("Time")
                        .HasColumnType("datetime2")
                        .HasColumnName("time");

                    b.Property<int>("Tray")
                        .HasColumnType("int")
                        .HasColumnName("tray");

                    b.HasKey("Id");

                    b.ToTable("data");
                });

            modelBuilder.Entity("Stiffiner_Inspection.Models.Entity.Error", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("DataId")
                        .HasColumnType("bigint")
                        .HasColumnName("data_id");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("DataId");

                    b.ToTable("errors");
                });

            modelBuilder.Entity("Stiffiner_Inspection.Models.Entity.ErrorCode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ErrorContent")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("error_content");

                    b.HasKey("Id");

                    b.ToTable("error_code");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ErrorContent = "black dot"
                        },
                        new
                        {
                            Id = 2L,
                            ErrorContent = "dirty"
                        },
                        new
                        {
                            Id = 3L,
                            ErrorContent = "glue"
                        },
                        new
                        {
                            Id = 4L,
                            ErrorContent = "ng sus position"
                        },
                        new
                        {
                            Id = 5L,
                            ErrorContent = "ng hole"
                        },
                        new
                        {
                            Id = 6L,
                            ErrorContent = "ng tape position"
                        },
                        new
                        {
                            Id = 7L,
                            ErrorContent = "scratch"
                        },
                        new
                        {
                            Id = 8L,
                            ErrorContent = "sus black dot"
                        },
                        new
                        {
                            Id = 9L,
                            ErrorContent = "white dot"
                        },
                        new
                        {
                            Id = 10L,
                            ErrorContent = "white line particle"
                        },
                        new
                        {
                            Id = 11L,
                            ErrorContent = "dent-tray1"
                        },
                        new
                        {
                            Id = 12L,
                            ErrorContent = "dent-tray2"
                        },
                        new
                        {
                            Id = 13L,
                            ErrorContent = "deform"
                        },
                        new
                        {
                            Id = 14L,
                            ErrorContent = "importinted"
                        },
                        new
                        {
                            Id = 15L,
                            ErrorContent = "curl tape"
                        },
                        new
                        {
                            Id = 16L,
                            ErrorContent = "curl sus"
                        },
                        new
                        {
                            Id = 17L,
                            ErrorContent = "ng tape"
                        });
                });

            modelBuilder.Entity("Stiffiner_Inspection.Models.Entity.Image", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("DataId")
                        .HasColumnType("bigint")
                        .HasColumnName("data_id");

                    b.Property<string>("Path")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("path");

                    b.HasKey("Id");

                    b.HasIndex("DataId");

                    b.ToTable("images");
                });

            modelBuilder.Entity("Stiffiner_Inspection.Models.Entity.Target", b =>
                {
                    b.Property<long>("TargetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("target_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TargetId"));

                    b.Property<DateTime>("Created_date")
                        .HasColumnType("DateTime")
                        .HasColumnName("created_date");

                    b.Property<int>("Target_qty")
                        .HasColumnType("int")
                        .HasColumnName("target_qty");

                    b.Property<DateTime>("Updated_date")
                        .HasColumnType("DateTime")
                        .HasColumnName("updated_date");

                    b.HasKey("TargetId");

                    b.ToTable("targets");
                });

            modelBuilder.Entity("Stiffiner_Inspection.Models.Entity.Error", b =>
                {
                    b.HasOne("Stiffiner_Inspection.Models.Entity.Data", "Data")
                        .WithMany("Errors")
                        .HasForeignKey("DataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Data");
                });

            modelBuilder.Entity("Stiffiner_Inspection.Models.Entity.Image", b =>
                {
                    b.HasOne("Stiffiner_Inspection.Models.Entity.Data", "Data")
                        .WithMany("Images")
                        .HasForeignKey("DataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Data");
                });

            modelBuilder.Entity("Stiffiner_Inspection.Models.Entity.Data", b =>
                {
                    b.Navigation("Errors");

                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
